const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={venues:[],filter:'dance',query:'',price:'all',favorites:new Set(JSON.parse(localStorage.getItem('zlachnyFavorites')||'[]'))};
const accent={dance:'#caff00',talk:'#ff38a8',date:'#ff4a65',live:'#38dbff',cinema:'#bd48ff',simple:'#ffc400',weird:'#00ff83',late:'#ff7100'};
function icon(id){return `<svg><use href="#${id}"/></svg>`}
function chisinauNow(){const n=new Date();$('#clock').textContent=new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Chisinau',hour:'2-digit',minute:'2-digit'}).format(n);const d=new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Chisinau',weekday:'long',day:'numeric',month:'long'}).format(n);$('#date').textContent=d.charAt(0).toUpperCase()+d.slice(1)}
function say(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2600)}
function filtered(){const q=state.query.toLowerCase();return state.venues.filter(v=>(state.filter==='all'||v.categories.includes(state.filter))&&(state.price==='all'||v.priceLevel===state.price)&&(!q||[v.name,v.type,v.district,v.address,v.description,...v.tags].join(' ').toLowerCase().includes(q)))}
function venueCard(v){const primary=v.categories[0]||'talk',color=accent[primary]||'#caff00',fav=state.favorites.has(v.id);return `<article class="venue" data-id="${v.id}" style="--accent:${color};--photo:url('${v.image}')"><div class="venue-photo"></div><span class="tag">${v.type}</span><button class="fav ${fav?'active':''}" data-fav="${v.id}" aria-label="В избранное">${icon('i-heart')}</button><div class="venue-content"><h3>${v.name}</h3><p>${v.description}</p><div class="venue-location">${icon('i-pin')}<span>${v.district} · ${v.hours}</span></div><div class="meta">${v.tags.slice(0,3).map(x=>`<span>${x}</span>`).join('')}<b>${v.priceLevel}</b></div></div></article>`}
function render(){const list=filtered(),cards=$('#cards');cards.classList.remove('loading');cards.innerHTML=list.length?list.map(venueCard).join(''):'<div class="empty-state">Ничего не найдено. Попробуй другой фильтр.</div>';$('#resultsCount').textContent=`Показано ${list.length} из ${state.venues.length}`;$$('[data-id]').forEach(c=>c.addEventListener('click',()=>openVenue(c.dataset.id)));$$('[data-fav]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const id=b.dataset.fav;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('zlachnyFavorites',JSON.stringify([...state.favorites]));render();say(state.favorites.has(id)?'Добавлено в избранное':'Удалено из избранного')}))}
function setFilter(filter){state.filter=filter;$$('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));render();$('#picks').scrollIntoView({behavior:'smooth',block:'start'})}
function openVenue(id){const v=state.venues.find(x=>x.id===id);if(!v)return;$('#venueModalPhoto').style.backgroundImage=`linear-gradient(180deg,transparent,rgba(0,0,0,.18)),url('${v.image}')`;$('#venueModalType').textContent=v.type;$('#venueModalName').textContent=v.name;$('#venueModalDescription').textContent=v.description;$('#venueDetails').innerHTML=`<div class="detail"><span>Район</span><b>${v.district}</b></div><div class="detail"><span>Адрес</span><b>${v.address}</b></div><div class="detail"><span>Часы</span><b>${v.hours}</b></div><div class="detail"><span>Бюджет</span><b>${v.priceLevel}</b></div><div class="detail"><span>Категории</span><b>${v.tags.join(' · ')}</b></div>`;$('#venueVerification').textContent=v.status==='verified'?`Проверено: ${v.verifiedAt}`:'Демо-запись. Адрес, график и ссылки ещё не подтверждены источниками.';$('#venueModal').classList.add('show')}
function buildRoute(){const selectedBudget=$('#budget').value;let pool=state.venues.filter(v=>selectedBudget==='all'||v.priceLevel===selectedBudget);if(!pool.length)pool=state.venues;const energy=$('#energy').value,company=$('#company').value;const pick=(cats,used=[])=>pool.find(v=>cats.some(c=>v.categories.includes(c))&&!used.includes(v.id))||pool.find(v=>!used.includes(v.id))||pool[0];const first=pick(energy==='calm'?['talk','date']:['talk','simple']);const second=pick(energy==='wild'?['dance','live']:energy==='calm'?['cinema','live']:['live','dance','cinema'],[first.id]);const third=pick(['late','simple'],[first.id,second.id]);const title=(energy==='wild'?'Сегодня без тормозов':energy==='calm'?'Красиво и без суеты':'Сначала культурно')+(company==='couple'?' · вдвоём':company==='solo'?' · соло':' · своей компанией');$('#result').innerHTML=`<div class="result-title">Твой сценарий: «${title}»</div><div class="route-line"><div class="stop"><small>20:00 · РАЗОГРЕВ</small><b>${first.name}</b><span>${first.type} · ${first.priceLevel}</span></div><div class="stop"><small>22:30 · ГЛАВНОЕ</small><b>${second.name}</b><span>${second.type} · ${second.priceLevel}</span></div><div class="stop"><small>01:30 · ФИНАЛ</small><b>${third.name}</b><span>${third.type} · ${third.priceLevel}</span></div></div>`;$('#result').classList.add('show');$('#result').scrollIntoView({behavior:'smooth',block:'nearest'})}
async function init(){chisinauNow();setInterval(chisinauNow,30000);try{const r=await fetch('venues.json?v=7',{cache:'no-store'});if(!r.ok)throw new Error('data');state.venues=(await r.json()).items||[];render()}catch(e){$('#cards').innerHTML='<div class="empty-state">Не удалось загрузить файл данных. Обнови страницу.</div>';$('#resultsCount').textContent='Ошибка загрузки'}
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));$('#resetFilter').addEventListener('click',()=>{state.filter='all';state.query='';state.price='all';$('#searchInput').value='';$('#priceFilter').value='all';$$('[data-filter]').forEach(x=>x.classList.remove('active'));render()});$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;render()});$('#priceFilter').addEventListener('change',e=>{state.price=e.target.value;render()});$$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));$('#build').addEventListener('click',buildRoute);$$('[data-map]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();$('#mapModal').classList.add('show')}));$$('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).classList.remove('show')));$$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('show')}));document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal.show').forEach(m=>m.classList.remove('show'))})}
document.addEventListener('DOMContentLoaded',init);