const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={venues:[],category:'all',district:'all',type:'all',music:'all',price:'all',openNow:false,kitchen:false,hideDemo:true,query:'',atmosphere:'all',favorites:new Set(JSON.parse(localStorage.getItem('zlachnyFavorites')||'[]')),map:null,markers:[]};
const accents={dance:'#caff00',talk:'#ff3d9d',date:'#ff6175',live:'#44d8ff',cinema:'#bd55ff',simple:'#ffcf35',weird:'#00ff9a',late:'#ff8a22',terrace:'#ff5aa9'};
const icon=id=>`<svg><use href="#${id}"/></svg>`;
const statusRank={verified:0,partial:1,demo:2};
const statusLabel={verified:'ПРОВЕРЕНО',partial:'ЧАСТИЧНО',demo:'ДЕМО'};
const safe=v=>v===null||v===undefined||v===''?'Не подтверждено':v;
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2400)}
function localNow(){return new Date(new Date().toLocaleString('en-US',{timeZone:'Europe/Chisinau'}))}
function isOpenNow(v){const now=localNow(),slot=v.schedule?.[String(now.getDay())];if(!slot)return false;const mins=now.getHours()*60+now.getMinutes(),parse=t=>{const [h,m]=t.split(':').map(Number);return h*60+m};const open=parse(slot[0]),close=parse(slot[1]);return close>open?mins>=open&&mins<close:mins>=open||mins<close}
function validateVenue(v){const required=['id','name','type','categories','district','address','coordinates','hoursLabel','status','sources'];const missing=required.filter(k=>v[k]===undefined||v[k]===null);if(missing.length){console.warn('Venue skipped: missing fields',v?.id,missing);return false}if(!Array.isArray(v.categories)||!Array.isArray(v.sources)||!Number.isFinite(v.coordinates.lat)||!Number.isFinite(v.coordinates.lng)){console.warn('Venue skipped: invalid structure',v?.id);return false}if(v.status==='verified'&&(!v.verifiedAt||!v.sources.length)){console.warn('Venue skipped: verified item without evidence',v?.id);return false}return true}
function filteredVenues(){const q=state.query.trim().toLowerCase();return state.venues.filter(v=>(!state.hideDemo||v.status!=='demo')&&(state.category==='all'||v.categories.includes(state.category))&&(state.district==='all'||v.district===state.district)&&(state.type==='all'||v.type===state.type)&&(state.music==='all'||v.music.includes(state.music))&&(state.price==='all'||v.priceLevel===state.price)&&(!state.openNow||isOpenNow(v))&&(!state.kitchen||v.kitchen===true)&&(!q||[v.name,v.type,v.district,v.address,v.description,...v.categories,...v.atmospheres,...v.tags,...v.music].join(' ').toLowerCase().includes(q))&&(state.atmosphere==='all'||v.atmospheres.includes(state.atmosphere))).sort((a,b)=>(statusRank[a.status]??9)-(statusRank[b.status]??9)||a.name.localeCompare(b.name,'ru'))}
function photoStyle(v){return v.image?`url('${v.image}')`:`linear-gradient(135deg,#181023,#071725 55%,#0a0b10)`}
function money(v){return Number.isFinite(v.averageBillMDL)?`${v.averageBillMDL} MDL`:'чек уточняется'}
function rating(v){return Number.isFinite(v.rating)?`<div class="rating">${icon('i-star')}<b>${v.rating.toFixed(1)}</b>${Number.isFinite(v.reviewsCount)?`<span>(${v.reviewsCount})</span>`:''}</div>`:'<div class="rating muted-rating">Рейтинг не импортирован</div>'}
function card(v){const key=v.categories[0]||'talk',color=accents[key]||'#ff3d9d',fav=state.favorites.has(v.id),open=isOpenNow(v),photoNote=v.imageStatus==='illustrative'?'<span class="image-note">ФОТО-ИЛЛЮСТРАЦИЯ</span>':'';return `<article class="venue status-${v.status}" data-venue="${v.id}" style="--accent:${color};--photo:${photoStyle(v)}"><div class="venue-photo"></div><div class="venue-top"><div class="tag-stack"><span class="quality-badge ${v.status}">${statusLabel[v.status]||v.status}</span><span class="tag">${v.type}${open?' · ОТКРЫТО':''}</span></div><button class="fav ${fav?'active':''}" data-fav="${v.id}" aria-label="Избранное">${icon('i-heart')}</button></div>${photoNote}<div class="venue-content"><h3>${v.name}</h3><p>${v.description}</p><div class="venue-line">${icon('i-pin')}<span>${v.district} · ${v.hoursLabel}</span></div>${rating(v)}<div class="meta">${v.tags.slice(0,3).map(t=>`<span>${t}</span>`).join('')}<b>${money(v)}</b></div></div></article>`}
function render(){const list=filteredVenues(),realCount=state.venues.filter(v=>v.status!=='demo').length,verifiedCount=state.venues.filter(v=>v.status==='verified').length;$('#cards').classList.remove('loading');$('#cards').innerHTML=list.length?list.map(card).join(''):'<div class="empty">Ничего не найдено. Сбрось часть фильтров.</div>';$('#resultsCount').textContent=`Показано ${list.length} · реальных карточек ${realCount} · полностью проверено ${verifiedCount}`;$('#mapCount').textContent=`${list.length} точек`;$$('[data-venue]').forEach(el=>el.addEventListener('click',()=>openVenue(el.dataset.venue)));$$('[data-fav]').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();const id=btn.dataset.fav;state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('zlachnyFavorites',JSON.stringify([...state.favorites]));render();toast(state.favorites.has(id)?'Добавлено в избранное':'Удалено из избранного')}));renderMap(list)}
function setCategory(value){state.category=value;$$('[data-category]').forEach(b=>b.classList.toggle('active',b.dataset.category===value));render()}
function sourceLinks(v){return (v.sources||[]).map(s=>`<a href="${s.url}" target="_blank" rel="noopener">${s.label}</a>`).join('')}
function openVenue(id){const v=state.venues.find(x=>x.id===id);if(!v)return;$('#modalPhoto').style.backgroundImage=`linear-gradient(180deg,transparent,rgba(0,0,0,.22)),${photoStyle(v)}`;$('#modalType').innerHTML=`<span class="quality-badge ${v.status}">${statusLabel[v.status]||v.status}</span> ${v.type}${v.imageStatus==='illustrative'?' · фото-иллюстрация':''}`;$('#modalName').textContent=v.name;$('#modalDescription').textContent=v.description;$('#modalDetails').innerHTML=[['Район',v.district],['Адрес',v.address],['Часы',v.hoursLabel],['Средний чек',money(v)],['Музыка',v.music.length?v.music.join(' · '):'Не подтверждено'],['Кухня',v.kitchen===true?'Да':v.kitchen===false?'Нет':'Не подтверждено'],['Возраст',safe(v.age)],['Бронь',safe(v.booking)],['Телефон',safe(v.phone)]].map(([a,b])=>`<div class="detail"><span>${a}</span><b>${b}</b></div>`).join('');setLink($('#modalMap'),v.mapUrl);setLink($('#modalWebsite'),v.website||v.instagram);const conf={high:'высокая',medium:'средняя',none:'нет'}[v.confidence]||v.confidence;$('#modalVerification').innerHTML=`<b>${statusLabel[v.status]||v.status}</b> · уверенность: ${conf}. ${v.verifiedAt?`Проверено ${v.verifiedAt}. `:''}${v.verificationNote||''}`;$('#modalSources').innerHTML=v.sources?.length?`<span>Источники</span>${sourceLinks(v)}`:'<span>Источники не добавлены</span>';$('#venueModal').classList.add('show')}
function setLink(el,url){if(url){el.href=url;el.classList.remove('disabled')}else{el.removeAttribute('href');el.classList.add('disabled')}}
function fillSelect(id,values,label){const el=$(id);el.innerHTML=`<option value="all">${label}</option>`+[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ru')).map(x=>`<option value="${x}">${x}</option>`).join('')}
function buildCollections(){const defs=[['Где потанцевать в эти выходные',['dance']],['Коктейльные бары с атмосферой',['talk','date']],['Красивый вечер на террасе',['terrace','date']]];$('#collectionsList').innerHTML=defs.map(([title,cats])=>{const items=state.venues.filter(v=>v.status!=='demo'&&cats.some(c=>v.categories.includes(c))).slice(0,4),photo=items[0]?.image||'';return `<button class="collection-item" data-collection="${cats[0]}"><span class="collection-photo" style="background-image:${photo?`url('${photo}')`:'linear-gradient(135deg,#281124,#0b1b27)'}"></span><span><h3>${title}</h3><p>${items.map(x=>x.name).slice(0,2).join(' · ')||'Подборка пополняется'}</p></span><span class="collection-count">${items.length} мест</span></button>`}).join('');$$('[data-collection]').forEach(b=>b.addEventListener('click',()=>{setCategory(b.dataset.collection);$('#places').scrollIntoView({behavior:'smooth'})}))}
function renderMap(list){if(window.L){if(!state.map){$('#map').innerHTML='';state.map=L.map('map',{zoomControl:true,attributionControl:false}).setView([47.0105,28.8638],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19}).addTo(state.map)}state.markers.forEach(m=>m.remove());state.markers=list.map(v=>{const marker=L.circleMarker([v.coordinates.lat,v.coordinates.lng],{radius:8,color:'#fff',weight:2,fillColor:accents[v.categories[0]]||'#ff3d9d',fillOpacity:1}).addTo(state.map);marker.bindPopup(`<b>${v.name}</b><br>${statusLabel[v.status]} · ${v.type}<br>${money(v)}`);marker.on('click',()=>openVenue(v.id));return marker});setTimeout(()=>state.map.invalidateSize(),50)}else{const box=$('#mapFallback');box.innerHTML=list.map(v=>{const x=20+((v.coordinates.lng-28.80)/.13)*60,y=80-((v.coordinates.lat-46.97)/.09)*60;return `<button class="fallback-pin" data-map-venue="${v.id}" style="left:${Math.max(6,Math.min(94,x))}%;top:${Math.max(7,Math.min(93,y))}%"></button>`}).join('');$$('[data-map-venue]').forEach(b=>b.addEventListener('click',()=>openVenue(b.dataset.mapVenue)))}}
function buildRoute(){let pool=filteredVenues().filter(v=>v.status!=='demo');if(!pool.length)pool=state.venues.filter(v=>v.status!=='demo');const budget=$('#routeBudget').value;if(budget!=='all'){const budgetPool=pool.filter(v=>v.priceLevel===budget);if(budgetPool.length)pool=budgetPool}if(!pool.length){toast('Для этих условий пока нет проверенных мест.');return}const energy=$('#energy').value,company=$('#company').value,pick=(cats,used=[])=>pool.find(v=>cats.some(c=>v.categories.includes(c))&&!used.includes(v.id))||pool.find(v=>!used.includes(v.id))||pool[0],first=pick(energy==='calm'?['talk','date','terrace']:['talk','terrace']),second=pick(energy==='wild'?['dance','live']:energy==='calm'?['terrace','cinema','live']:['live','dance','terrace'],[first.id]),third=pick(['late','talk'],[first.id,second.id]),title=(energy==='wild'?'Сегодня без тормозов':energy==='calm'?'Красиво и без суеты':'Сначала культурно')+(company==='couple'?' · вдвоём':company==='solo'?' · соло':' · своей компанией');$('#routeResult').innerHTML=`<div class="route-title">Твой сценарий: «${title}»</div><div class="route-line">${[[first,'20:00 · РАЗОГРЕВ'],[second,'22:30 · ГЛАВНОЕ'],[third,'01:30 · ФИНАЛ']].map(([v,t])=>`<button class="route-stop" data-route-venue="${v.id}"><small>${t}</small><b>${v.name}</b><span>${v.type} · ${money(v)}</span></button>`).join('')}</div>`;$('#routeResult').classList.add('show');$$('[data-route-venue]').forEach(b=>b.addEventListener('click',()=>openVenue(b.dataset.routeVenue)))}
function reset(){Object.assign(state,{category:'all',district:'all',type:'all',music:'all',price:'all',openNow:false,kitchen:false,hideDemo:true,query:'',atmosphere:'all'});$$('select').forEach(s=>{if(['energy','company','routeBudget'].includes(s.id))return;s.value='all'});$('#searchInput').value='';$('#heroSearchInput').value='';$('#openNowFilter').checked=false;$('#kitchenFilter').checked=false;$('#hideDemoFilter').checked=true;$$('[data-atmosphere]').forEach(b=>b.classList.remove('active'));setCategory('all')}
async function init(){try{const r=await fetch('venues-v9.json?v=9',{cache:'no-store'});if(!r.ok)throw new Error('data');const raw=(await r.json()).items||[];state.venues=raw.filter(validateVenue);fillSelect('#districtFilter',state.venues.filter(v=>v.status!=='demo').map(v=>v.district),'Все районы');fillSelect('#typeFilter',state.venues.filter(v=>v.status!=='demo').map(v=>v.type),'Все типы');fillSelect('#musicFilter',state.venues.filter(v=>v.status!=='demo').flatMap(v=>v.music),'Любая музыка');buildCollections();render()}catch(e){console.error(e);$('#cards').innerHTML='<div class="empty">Не удалось загрузить базу данных.</div>';$('#resultsCount').textContent='Ошибка загрузки'}
$$('[data-category]').forEach(b=>b.addEventListener('click',()=>setCategory(b.dataset.category)));[['#districtFilter','district'],['#typeFilter','type'],['#musicFilter','music'],['#priceFilter','price']].forEach(([id,key])=>$(id).addEventListener('change',e=>{state[key]=e.target.value;render()}));$('#openNowFilter').addEventListener('change',e=>{state.openNow=e.target.checked;render()});$('#kitchenFilter').addEventListener('change',e=>{state.kitchen=e.target.checked;render()});$('#hideDemoFilter').addEventListener('change',e=>{state.hideDemo=e.target.checked;render()});$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;render()});$('#heroSearchForm').addEventListener('submit',e=>{e.preventDefault();state.query=$('#heroSearchInput').value;$('#searchInput').value=state.query;render();$('#places').scrollIntoView({behavior:'smooth'})});$('#resetFilters').addEventListener('click',reset);$$('[data-atmosphere]').forEach(b=>b.addEventListener('click',()=>{const value=b.dataset.atmosphere;state.atmosphere=state.atmosphere===value?'all':value;$$('[data-atmosphere]').forEach(x=>x.classList.toggle('active',x.dataset.atmosphere===state.atmosphere));render();$('#places').scrollIntoView({behavior:'smooth'})}));$$('[data-scroll]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));$('#buildRoute').addEventListener('click',buildRoute);$$('[data-close]').forEach(b=>b.addEventListener('click',()=>$('#'+b.dataset.close).classList.remove('show')));$('#venueModal').addEventListener('click',e=>{if(e.target===$('#venueModal'))$('#venueModal').classList.remove('show')});document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#venueModal').classList.remove('show')});$('#newsletterForm').addEventListener('submit',e=>{e.preventDefault();e.currentTarget.reset();toast('Подписка будет подключена после запуска проверенной базы.')})}
document.addEventListener('DOMContentLoaded',init);